time_series_columns = [
    'System Price',
    'Total Vol', 
    'NO Buy Vol',
    'NO Sell Vol',
    'SE Buy Vol',
    'SE Sell Vol',
    'DK Buy Vol',
    'DK Sell Vol',
    'FI Buy Vol',
    'FI Sell Vol',
    'Nordic Buy Vol',
    'Nordic Sell Vol',
    'Baltic Buy Vol',
    'Baltic Sell Vol',
    'T Hamar',
    'T Krsand',
    'T Namsos',
    'T Troms',
    'T Bergen',
    'T Nor',
    'NO Hydro',
    'SE Hydro',
    'FI Hydro',
    'Total Hydro',
    'NO Hydro Dev',
    'SE Hydro Dev',
    'FI Hydro Dev',
    'Total Hydro Dev',
    'Wind DK',
    'Curve Demand',
    'SE1',
    'SE2',
    'SE3',
    'SE4',
    'FI',
    'DK1',
    'DK2',
    'Oslo',
    'Kr.sand',
    'Bergen',
    'Molde',
    'Tr.heim',
    'Tromsø']

date_descriptive_colums = [
    'Week',
    'Month',
    'Season',
    'Weekday',
    'Weekend',
    'Holiday'
]